### ISSUE TITLE
It only export 500 records or results to csv

### ISSUE THREAD

**Issue by vg15** [minewhat/es-csv-exporter#1]
Hi , 
First of all thanks for developing this most awaited feature .
I installed this plugin but I can only see 500 records out of 7000 in my CSV . So this is what I have done , I fire a query in Discover tab and it returns 7000 count . I hit "Copy to Clipboard" , then paste results in CSV but I can only see 500 records .This is it , or do we need to do anything extra for this plugin ?

**Comment by janakg** [comment]
Hi, Since it is a client only solution, it relies on the visible results, means it scraps the data from the HTML table, so you need to load the results to the table before you hit  "Copy to Clipboard". 
I hope it helps.

**Comment by vg15** [comment]
Is there any way to increase the no. of rows displayed in discover table .
By default it is 50 , I mean before scroll the first result is 50 rows ,
can i increase this to 1000 ?

On Thu, Jan 7, 2016 at 12:28 PM, Janakiram Ganesan <notifications@github.com

> wrote:
> 
> Hi, Since it is a client only solution, it relies on the visible results,
> means it scraps the data from the HTML table, so you need to load the
> results to the table before you hit "Copy to Clipboard".
> I hope it helps.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/minewhat/es-csv-exporter/issues/1#issuecomment-169573979
> .

## 

_Regards,_
_Vikas Gopal_

**Comment by giray** [comment]
@vg15 you can go into "Settings" -> "Advanced" -> discover:sampleSize (Default: 500)

**Comment by vg15** [comment]
I got it thanks @giray

On Wed, Feb 10, 2016 at 3:31 AM, giray notifications@github.com wrote:

> @vg15 https://github.com/vg15 you can go into "Settings" -> "Advanced"
> -> discover:sampleSize (Default: 500)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/minewhat/es-csv-exporter/issues/1#issuecomment-182097306
> .

## 

_Regards,_
_Vikas Gopal_

**Comment by orlybur** [comment]
Hi, I increased the discover:sampleSize (Default: 500) to 5500 but when I click on copy to clipboard, I only get 1000 rows. Any idea why and how I can fix it?

**Comment by sumit0k** [comment]
@orlybur Can you verify that the number of rows in the visible results are more than 1000?
