### ISSUE TITLE
Spaces stripped out field values

### ISSUE THREAD

**Issue by giray** [minewhat/es-csv-exporter#2]
On 

CHROME VERSION 48.0.2564.103
OS VERSION  Linux: 4.2.0-27-generic

the spaces in individual fields/columns get stripped, so if the value in the field was

   "Big Bad Wolf"

when I select "copy to clipboard" and paste it I get

   "BigBadWolf"

Kibana 4.4.0 / Elastic 2.2.0

**Comment by tangfucius** [comment]
Yeah having the same problem on OS X too

**Comment by janakg** [comment]
Thanks for raising this issue. Apologies for the delay,  I have fixed it and will update the chrome store by today
