### ISSUE TITLE
Great product!

### ISSUE THREAD

**Issue by kelsorj** [minewhat/es-csv-exporter#3]
We just upgraded to kibana 4.3.2 to get some of the functionality that monitor provides.  But it looks like it broke csv export.  Could you look to see if there's any easy fix to get it updated to use 4.3.2?

**Comment by janakg** [comment]
Thanks. I have tested today on Kibana 4.3.3 and 4.4.2, it works. Can you update to a stable version from elastic.co and let me know if you are facing this issue?

**Comment by kelsorj** [comment]
It looks like the issue isn't from our upgrade to a new version of Kibana but trying to get the data out of a visualization versus trying to get it out of a discovery.  Pulling the data out of discover works perfectly, thanks for making a great kibana add-on!
