### ISSUE TITLE
Problem export json

### ISSUE THREAD

**Issue by jontra** [minewhat/es-csv-exporter#4]
Hi,

When printing json to the log, the exporter replace commas with semicolons, and turn the json to be invalid.
`//Replace comma with colon`
`h = h.replace(/,/g, ";");`

Why did you choose to replace ',' with ';'?

Awesome extension BTW!
Thanks!

**Comment by jontra** [comment]
OK, you wanted to make sure its in csv format.
I don't really need it in csv format, so I removed this replace locally.
I think it would be nice to have an option just to export raw data (not csv format)

**Comment by janakg** [comment]
Yes, you are right , it has to be replaced to support CSV format. When I get time, will provide an additional option to export as raw data. So it is a new feature request, moving the state to closed. Thanks, Ram
